### ISSUE TITLE
serialport-0.4.7 test suite failure

### ISSUE THREAD

**Issue by peti** [jputcu/serialport#25]
I'm getting the following error trying to run the test suite on Linux:

    Running 1 test suites...
    Test suite Tests: RUNNING...
    Tests: user error (Pattern match failure in do expression at tests/Tests.hs:105:3-27)
    Test suite Tests: FAIL

The complete build log is at http://hydra.cryp.to/build/496544/nixlog/1/raw.

**Comment by jputcu** [comment]
It is not clear from the output if you passed the same cabal test arguments as stated in `README.md`:
`cabal test --test-options="/dev/ttyACM0 /dev/ttyUSB0"`?
Both serial ports should link to an Arduino Leonardo with the correct firmware and FTDI breakout.

**Comment by peti** [comment]
ah, okay. We cannot satisfy these constraints. I guess we'll have to disable the test suite in NixOS then. Thank you for the quick response!
