### ISSUE TITLE
Serial `recv` catches too many exceptions

### ISSUE THREAD

**Issue by mryndzionek** [jputcu/serialport#34]
[Here](https://github.com/jputcu/serialport/blob/master/System/Hardware/Serialport/Posix.hsc#L99) it seems that it would be better to catch the exceptions more selectively. For example if one is reading in an infinite loop and then the port disappears (USB serial port converter gets disconnected etc) the loop turns into a non-blocking loop consuming all the CPU. In other words there is no way of telling if the B.empty is a timeout, or something more severe.

**Comment by jputcu** [comment]
Hello, Sorry, but I've more or less abandoned this project going back to C++.

**Comment by mryndzionek** [comment]
Fair enough :) I'll try to solve this myself.
